### ISSUE TITLE
Create branch predictors

### ISSUE THREAD

**Issue by Gripnook** [Gripnook/mips-pipelined-processor#20]
Each member will create a branch predictor for performance testing.
Make sure to use the same interface as the existing predict not taken and predict taken predictors, and put your module in the branch_predictor directory. Also, add your component declaration to the branch_prediction package so we don't have to re-declare them in the processor.

Comment here on what type of predictor you're implementing.

**Comment by SebastianPilarski** [comment]
I'll do correlating predictor

**Comment by Gripnook** [comment]
Note: We should check the terminology for the terms we use (BHT, etc). Also, we should remove the previous_prediction input to predictors.
